---
- include_vars: vars.yml

- name: install the build essential packages (apt)
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ pkg_build_essential_apt_packages }}"
  when: ansible_distribution in [ "Debian", "Ubuntu" ]

- name: install the build essential packages (yum)
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ pkg_build_essential_yum_packages }}"
  when: ansible_distribution in [ "Fedora", "RedHat", "CentOS" ]
