---
- name: Get glide version
  shell: >
    curl -sI {{ glide_repository_url }}/releases/latest | awk -F'/' '/^Location:/{print $NF}'
  register: glide_version

- name: Download glide
  get_url: url={{ glide_repository_url }}/releases/download/{{ glide_version.stdout }}/glide-{{ glide_version.stdout }}-linux-amd64.tar.gz dest=/tmp/glide-{{ glide_version.stdout }}-linux-amd64.tar.gz

- name: Extract glide
  command: tar zxvf /tmp/glide-{{ glide_version.stdout }}-linux-amd64.tar.gz chdir=/tmp

- name: Copy glide
  shell: mv /tmp/linux-amd64/glide {{ glide_dest }} && chmod a+x {{ glide_dest }}
