---
- hosts: 127.0.0.1
  connection: local
  become: yes
  become_user: root
  roles:
    - { role: pkg }
    - { role: pkg/build-tools }

- hosts: 127.0.0.1
  connection: local
  roles:
    - { role: vim/vundle }
    - { role: vim/vundle }
    - { role: golang/get }
