---
- hosts: all
  become: yes
  become_user: root
  roles:
    - { role: pkg }
    - { role: pkg/build-essential }
    - { role: pkg/devel-essential }

- hosts: all
  become: yes
  become_user: root
  roles:
    - { role: mosh }
    - { role: docker }
    - { role: docker/compose }
    - { role: zsh, zsh_users: [] }
    - { role: python/pip }
    - { role: jq }
    - { role: tmux }

