---
- hosts: all
  become: yes
  become_user: root
  roles:
    - { role: pkg }
    - { role: pkg/build-essential }
    - { role: pkg/devel-essential }

- hosts: all
  become: yes
  become_user: root
  roles:
    - { role: mosh }
    - { role: zsh, zsh_users: [] }
    - { role: docker }
    - { role: docker/compose }
    - { role: jq }
    - { role: tmux }
    - { role: direnv }
    - { role: ghq }
    - { role: peco }

- hosts: all
  remote_user: kaneshin
  roles:
    - { role: z }
    - { role: rbenv, rbenv_versions: [] }
    - { role: pyenv, pyenv_versions: [] }
    - { role: goenv, goenv_versions: [] }
    - { role: nodenv, nodenv_versions: [] }
    - { role: dotfiles }
