---
- name: Get ghq version
  shell: >
    curl -sI {{ ghq_repository_url }}/releases/latest | awk -F'/' '/^Location:/{print $NF}'
  register: ghq_version

- name: Download ghq
  get_url: url={{ ghq_repository_url }}/releases/download/{{ ghq_version.stdout }}/{{ ghq_archive }}.zip dest=/tmp/{{ ghq_archive }}.zip

- name: Extract ghq
  command: unzip /tmp/{{ ghq_archive }}.zip -d {{ ghq_archive }} chdir=/tmp

- name: Copy ghq
  shell: mv /tmp/{{ ghq_archive }}/ghq {{ ghq_dest }} && chmod a+x {{ ghq_dest }}
