---
- name: Install fisherman
  shell: curl -Lo {{ fisherman_fisher_functions }} --create-dirs git.io/fisherman;
  args:
    creates: "{{ fisherman_fisher_functions }}"

- name: Setup config.fish
  shell: >
    echo 'not status --is-interactive; exit' >> {{ fisherman_fish_config }};
    curl -L git.io/confd >> {{ fisherman_fish_config }} && touch {{ fisherman_confd_once }}
  args:
    creates: "{{ fisherman_confd_once }}"

- name: Install fisher plugins (failed_when)
  shell: /usr/bin/fish -c "fisher {{ item }}"
  failed_when: false
  with_items: "{{ fisherman_plugins }}"
  when: fisherman_plugins | length > 0
