---
- name: install the devel essential packages (apt)
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ pkg_devel_essential_packages }}"
  when: ansible_distribution in [ "Debian", "Ubuntu" ]

- name: install the devel essential packages (yum)
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ pkg_devel_essential_packages }}"
  when: ansible_distribution in [ "Fedora", "RedHat", "CentOS" ]
