---
- name: install zsh
  apt: name=zsh state=present
  when: ansible_os_family == 'Debian'

- name: change shell to zsh
  user:
    name: "{{ item }}"
    shell: /usr/bin/zsh
  with_items: "{{ zsh_users }}"
  when: zsh_users | length > 0
