---
- name: install zsh (apt)
  apt: name=zsh state=present
  when: ansible_distribution in [ "Debian", "Ubuntu" ]

- name: install zsh (yum)
  yum: name=zsh state=present
  when: ansible_distribution in [ "Fedora", "RedHat", "CentOS" ]

- name: change shell to zsh
  user:
    name: "{{ item }}"
    shell: /usr/bin/zsh
  with_items: "{{ zsh_users }}"
  when: zsh_users | length > 0
