---
- name: Install anyenv
  git: repo="{{ anyenv_repository_url }}" dest="{{ anyenv_dir }}"

- template: src=profile.j2 dest={{ anyenv_profile }}

- name: Install envs
  shell: >
    source {{ anyenv_profile }};
    {{ anyenv_dir }}/bin/anyenv install {{ item }};
  args:
    creates: "{{ anyenv_dir }}/envs/{{ item }}"
  with_items: "{{ anyenv_envs }}"
  when: anyenv_envs | length > 0
