---
- include: debian.yml
  when: ansible_distribution in [ "Debian", "Ubuntu" ]

- include: centos.yml
  when: ansible_distribution in [ "Fedora", "RedHat", "CentOS" ]

- include: darwin.yml
  when: ansible_os_family == 'Darwin'

#- include: tmuxinator.yml
#  when: tmux_install_tmuxinator
#
#- include: tmuxp.yml
#  when: tmux_install_tmuxp
