---
- name: Install pyenv
  git: repo="{{ pyenv_repository_url }}" dest="{{ pyenv_dir }}"

- template: src=profile.j2 dest={{ pyenv_profile }}

- name: Install distributions
  shell: >
    source {{ pyenv_profile }};
    {{ pyenv_dir }}/bin/pyenv install {{ item }};
  with_items: "{{ pyenv_versions }}"
  when: pyenv_versions | length > 0
