---
- name: Install development tools
  apt: name={{ item }} state=present
  with_items:
    - autoconf
    - automake
    - bison
    - bzip2
    - cmake
    - ctags
    - diffstat
    - doxygen
    - flex
    - gcc
    - g++
    - gdb
    - gettext
    - git
    - indent
    - intltool
    - libbz2-dev
    - libffi-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - libtool
    - make
    - mercurial
    - patch
    - patchutils
    - sqlite3
    - subversion
    - tree
    - unzip
    - zlib1g-dev
