---
- name: install packages for docker
  apt: name={{ item }} state=present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common

- name: add the new GPG key.
  shell: curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -

- name: add an entry for your Debian operating system
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"

- name: update apt cache
  apt: update_cache=yes

- name: install docker-ce
  apt: name=docker-ce state=present

